### ISSUE TITLE
Characters linked to incorrect shared transfer stash

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#1]
Vanilla and mod characters in GrimDawn editor can get wrong shared stash file linked

If a mod character is loaded and then load command used to switch to vanilla characters, vanilla character gets mod shared stash (should get vanilla shared stash)

If mod character loaded with no mod picked, mod character will have vanilla shared stash assigned (should always be mod shared stash).

**Comment by Odie** [comment]
Fixed in 08d640c06b516476c944a4373a2637d32d3f7b69.

The editor will now load the vanilla stash by default. Unless:
1. The character file being loaded is in mod character and
2. A mod has been selected via "mod pick"

So you should be able to leave the mod settings alone now. Switching characters would result in the editor automatically picking the right stash file. =)

Just grab the new version and you should see the changes.
