### ISSUE TITLE
Feature request - Add ability to generate prefix and/or suffix to item creation

### ISSUE THREAD

**Issue by GrimDawn-max** [Odie/gd-edit#4]
Many items in game have affix, prefix or suffix descriptors. Currently the editor creates a vanilla version of an item without additional (optional) descriptors. Would like ability to add descriptors to items if possible. Examples shown below

https://www.grimtools.com/db/items/8997 (called affixes here)
https://www.grimtools.com/db/search?query=Impervious&in_description=1&exact_match=0 (magic)
https://www.grimtools.com/db/search?query=%22Of%20Hungering%20Rifts%22&in_description=1&exact_match=0

GDStash has drop down options in item creation tab to see all available types. Patch 1.1.7.0 is supposed to remove some of these, so maybe wait till then before looking in to

**Comment by Odie** [comment]
I think the editor has supported this since its very first release?

For example, you can do:
```
> set inv/0/items "Gargoyle Girdle of Hungering Rifts"
```

The editor knows about all the affixes. You can freely mix and match them and it will try its best to pull apart the name, figure out if there is a prefix or suffix in there, and assemble that item for you.

Do note that it doesn't really respect item generation rules. So, although "Hungering Rifts" is supposed to be on belts and jewels only, the editor *will* generate a "Vampiric Legion Greaves of Hungering Rifts" if you ask it to, regardless of how little sense that may make. The game also appears to honor those strange combinations. It just won't ever generate that item on its own.

Also, the editor always loads the game db on startup. The affixes that it knows about will match your version of the game. So, hopefully, things will always *mostly work*. x)

**Comment by GrimDawn-max** [comment]
> I think the editor has supported this since its very first release?
Yes it is already there and working as I'd expect. I tested after taking your suggestion up of looking more closely at the documentation for commands. I really need to slow down and read things :-)
